files:
  include: "src/assets/stylesheets/*.scss"
rules:
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  leading-zero:
    - 0
  nesting-depth:
    - 1
    -
      max-depth: 5
  quotes:
    - 1
    - style: double
  indentation:
    - 2
